modLoader="javafml"
loaderVersion="[43,)"
license="GNU GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/NicosaurusRex99/Jerry-s-Mod/issues"
[[mods]]
modId="jerrysmod"
version="${file.jarVersion}"
displayName="Jerry's Mod"
updateJSONURL="https://raw.githubusercontent.com/NicosaurusRex99/Nicusha-mod-assets/main/jerry_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jerrys-mod"
logoFile="logo.png"
credits="Thanks to sniper mine and hawaii beach for letting me do this!"
authors="Sniper_mine, Hawaii_Beach and NicosaurusRex99"
description='''
Made in honor of Jerry the noble slime!
'''

[[dependencies.jerrysmod]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.jerrysmod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
