modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/NicosaurusRex99/Jerry-s-Mod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/NicosaurusRex99/Nicusha-mod-assets/main/jerry_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jerrys-mod"
logoFile="logo.png"
credits="Thanks to sniper mine and hawaii beach for letting me do this!"
authors="${mod_authors}"
description='''${mod_description}'''
